# Generated by Django 4.0.4 on 2022-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
