# Generated by Django 4.0.4 on 2022-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_alter_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='isFav',
            field=models.BooleanField(default=False),
        ),
    ]
